version: "3"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    container_name: "mongodb"
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
  backend:
    container_name: "backend"
    build: ./cars-management
    restart: on-failure
    ports:
      - "8080:8080"
   
